# Generated by Django 4.2.1 on 2023-06-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_record_last_visit_record_next_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='last_visit',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='next_visit',
            field=models.DateField(blank=True),
        ),
    ]
