# Generated by Django 4.2.1 on 2023-06-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_record_last_visit_alter_record_next_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='created_at',
        ),
    ]
